---
frontendImage: lemonday/todo-frontend
frontendVersion: 35d0674d
frontendNodePort: 30080

backendImage: lemonday/todo-backend
backendVersion: 35d0674d

enabledFeatures:
  metrics: false
  ingress: false
