---
frontendImage: lemonday/todo-frontend
frontendVersion: bd81cbb7
frontendNodePort: 30080

backendImage: lemonday/todo-backend
backendVersion: bd81cbb7

enabledFeatures:
  metrics: false
  ingress: false
